apiVersion: apps/v1
kind: Deployment
metadata:
  name: processer
  labels:
    app: processer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processer
  template:
    metadata:
      labels:
        app: processer
    spec:
      containers:
        - name: processer
          image: username/processer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5